apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: default
spec:
  interval: 10m
  targetNamespace: default
  chart:
    spec:
      chart: podinfo
      version: '>=*-dev'
      sourceRef:
        kind: HelmRepository
        name: podinfo
