apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m0s
  url: oci://registry-1.docker.io/summers1971/podinfo
  ref:
    semver: 6.3.x

